name: example
description: "Example app for sound_waveform"
version: 1.1.0
repository: https://github.com/rafaelmaia8384/sound_waveform
publish_to: none

environment:
  sdk: ">=3.3.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  sound_waveform:
    path: ..

dev_dependencies:
  flutter_lints: ^5.0.0
